<?php die(); ?>
lang = Беларуская
Save = Запісаць
Remove = Выдаліць
Confirm removal = Пацьвердзіце выдаленне
Human code = Паверкавы код
Management = Кіраванне
Password = Пароль
keep authorization = трымаць дазвол
Enter = ўваходзьце
Comments = Каментары
Comment = Каментаваць
Meruert could not create system files; the root directory should be writeable = Не ўдаецца стварыць сыстэмныя файлы; каранёвая дырэкторыя павінна быць даступнай для запісу.
Start = Старт
Website name = Прыдумайце назву сайта
Admin password = Прызначце пароль адміністратара
Go = і пачынайце працаваць
Files = Файлы
One level up = На ўзровень вышэй
Root directory = Каранёвая папка
Choose directory: = Выбраць папку:
Open = Адчыніць
Upload: = Укласці:
Add directory name if you need to add a directory in the current one and upload files there: =Калі трэба дадаць папку ўнутры бягучай і загрузіць файлы ў яе, ўпішыце назвy папкі:
one more file = яшчэ адзін файл
Upload = Укласці
Preferences = Налады
Website name: = Назва сайта:
Admin password: = Пароль адміністратара:
allow comments = дазволіць каментары
Send comment notifications to the following email: = Адпраўляць абвяшчэння аб каментарах на наступны e-mail:
Posts per page: = Запісаў на старонку:
Design theme: = Тэма дызайну:
Interface language: = Мова інтэрфейсу:
secret blog = прыватны блог
New post = Новы запіс
Edit post = Рэдактаванне запісу
Title: = Загаловак:
Post text: = Тэкст запісу:
Add new topic (or few comma divided): = Дадайце новую тэму (калі некалькі, то праз коску):
or choose from saved ones: = або абярыце з існуючых:
Base part of post URL address: = Ключавая частка адрасу для запісу:
Show additional options = Паказаць дадатковыя опцыі запісу
Alternate text for TITLE tag: = Альтэрнатыўны тэкст для TITLE:
SEO keywords: = Ключавыя словы для пошукавых сістэм:
SEO description: = Апісанне для пошукавых сістэм:
store in drafts = пакуль пакінуць у чарнавіках
use as page not in the blog = не змяшчаць у блог: зрабіць простaй старонкай
link in the top menu = ссылка ў верхнім меню
link in the sidebar = ссылка ў бакавой калонцы
Post intro to be displayed in the blog instead of the text: = Тэкст, які будзе паказвацца ў стужцы замест асноўнага:
Hide additional options = Схаваць дадатковыя опцыі запісу
Done = Гатова
Reply to a comment: = Адказ на каментар:
Reply to your comment: = Адказ на ваш каментар:
Comment author: = Аўтар каментара:
E-mail of the comment author: = E-mail аўтара:
Website of the comment author: = Сайт аўтара:
Comment text: = Тэкст каментара:
Your reply: = Ваш адказ:
notify comment author about the reply = паведаміць аўтару каментара пра адказ
just remove the comment = проста выдаліць каментар
New comment: = Новы каментар:
New comment at: = Новы каментар па адрасе:
Continuing discussion: = Працяг абмеркавання:
Drafts = Чарнавікі
Find = Знайсці
January = студзені
February = лютага
March = сакавіка
April = красавіка
May = мая
June = чэрвеня
July = ліпеня
August = жніўня
September = верасня
October = кастрычніка
November = лістападзе
December = сьнежня
Full text = Поўны тэкст
Edit = Праўка
edit = рэд.
Your name: = Вас клічуць:
Your email (for notifications): = Ваш e-mail (для атрымання апавяшчэнняў):
Your website: = Ваш сайт:
Write a comment: = Напішыце каментарый:
Send = Адправіць
No posts here. = У гэтым раздзеле нічога няма.
Pages: = Старонкі:
Blog = Блог
Search = Пошук
Write = Напісаць
Exit = Выхад
Edit the comment = Рэдагаванне каментара
Alternative main page: = Альтэрнатыўная галоўная старонка:
Favourite = Абранае
in favourites = ў абраных запісах
Edit the sidebar = Бакавая калонка
Text before links: = Тэкст да спасылак:
Text after links: = Тэкст пасля спасылак:
Page suffix (e.g. .html): = Пашырэнне старонак (напрыклад, .html):
Profile photo: = Фотаздымак:
remove photo = выдаліць фота
secret post = таемная запіс
Secret posts = Таемныя запісы
Change publication date = Змяніць дату публікацыі
hide Blog link = хаваць спасылку на блог
hide Management link = хаваць спасылку на кіраванне
Powered by = Працуе на
Edit the top menu = Рэдагаванне меню

Edit the footer = Рэдагаванне падвала
Empty this field to reset the footer: = Пакіньце гэтае поле пустым, каб аднавіць стандартнае значэнне:
do not use rich text editor = не выкарыстоўваць рэдактар ​​пашыранага фарматавання
Place Youtube / Google Maps / audio code here: = Коды для ўстаўкі ролікаў з Youtube, Google Maps, музычных сэрвісаў:

Read from the start = Чытаць з пачатку
Usual blog order = Звычайны парадак запісаў
premoderate comments = каментары будуць чакаць вашай праверкі
Comments are premoderated. = Новыя каментары будуць чакаць праверкі.
— to moderate = — чакае праверкі
approve this comment = ўхваліць каментар
use social buttons = дадаваць сацыяльныя кнопкі

template = шаблон
Edit the current template = Рэдагаванне шаблону
HTML template: = Шаблон HTML:
Post / page template: = Шаблон запісы або старонкі:

raise updated posts = падымаць абнаўляюцца запісу
Language switchers: = Перамыкачы моў:
topics in sidebar = тэмы запісаў у бакавой калонцы

Posts = Запісы блога
Pages = Старонкі

hide RSS link = хаваць спасылку на RSS
hide Search link = хаваць спасылку на пошук
Copying page = Капіраванне старонкі
Copy this page = Капіяваць гэтую старонку
(Edit part) = (правіць фрагмент)
(Edit) = (рэдакцыя)
Editing part = Рэдагаванне фрагмента
Insert stats code = Уставіць код статыстыкі
stats code = код статыстыкі
kB = КБ
Remind password = Нагадаць пароль
Your email: = Ваш e-mail:
Email = E-mail
Check your mailbox. = Праверце электронную пошту.
: Password reminder = : напамін пароля
Your password: = Ваш пароль:
Send notifications to the following email: = Адпраўляць паведамлення на наступны e-mail:
allow comments for this entry = дазволіць каментары для гэтай запісу
make this entry visible for everyone = зрабіць гэты запіс бачнай для ўсіх
closed website = закрыты сайт
Editing meta = Мета-дадзеныя
Alternative URL = Альтэрнатыўны URL
Alternative heading = Альтэрнатыўны загаловак
Preface = Прадмова
Alternative title = Альтэрнатыўны TITLE
Keywords = Ключавыя словы
Description = Апісанне
Deferred post = Адкладзеная запіс
Create new folder = Стварыць новую папку
display only content in the selected language = адлюстроўваць толькі кантэнт на абраным мове
Post language: = Мова запісу:
post ratings = рэйтынгі запісаў
Ratings = Рэйтынгі

Create = Стварыць
create = стварыць
change = змяніць
(edit menu) = (правіць меню)
Editing menu = Рэдагаванне меню
log = лог
Log = Лог





(edit PHP code) = (рэдагаваць PHP-код)
PHP code = PHP-код

Edit the super menu = Рэдагаванне галоўнага меню
only positive ratings = толькі станоўчыя рэйтынгі
hide Favourite link = хаваць спасылку ў абранае
hide Secret posts link = хаваць спасылку на таемныя запісы
hide Drafts link = хаваць спасылку на чарнавікі
hide Files link = хаваць спасылку на файлы
hide Comments link = хаваць спасылку на каментары
hide Ratings link = хаваць спасылку на рэйтынгі

hide topic list = хаваць спіс тэм

Create new file = Стварыць новы файл
MB = МБ

Publish in = Месца публікацыі
main blog = асноўны блог
add a blog = дадаць блог
New blog title = Назва новага блога
blogs in sidebar = назвы блогаў у бакавой калонцы
blogs = блогі
topics = тэмы запісаў
Name = Назва
search in sidebar = пошук у бакавой калонцы

edit Meta = Meta-тэгі
Edit Meta = Meta-тэгі
Motto: = Дэвіз:
Confirm, please! = Пацвердзіце, калі ласка!
Reset the preferences = Скінуць налады

Nickname / name: = Імя або нік:
E-mail: = Электронны адрас:
Message: = Паведамленне:
Message from your website = Пісьмо з вашага сайта
Message sent. = Паведамленне адпраўлена.

Cancel = Адмена
make main page = зрабіць галоўнай старонкай сайта

Click to enlarge = Пстрыкніце, каб павялічыць

Record order: = Парадак запісаў:
usual = звычайны
from beginning = з пачатку
random = выпадковы
alphabetical = алфавітны
anti-alphabetical = антыалфавітны
by rating = па рэйтынгу

Pagination: = Нумарацыя старонак:
under the posts = пад запісамі
over and under the posts = над і пад запісамі
concise = лаканічная
none = адсутнічае
previous = папярэдняя
next = наступная
