<?php die(); ?>
lang = Eesti keel
Save = Salvesta
Remove = Kustuta
Confirm removal = Kinnita kustutamine
Human code = Kinnita, et oled inimene
Management = Korraladamine
Password = Salasõna
keep authorization = Jäta mind meelde
Enter = Sisene
Comments = Kommentaarid
Comment = Kirjuta kommentaar
Meruert could not create system files; the root directory should be writeable = Süüsteemi faile ei saa luua; põhikaust peab olema kirjutamiseks vaba.
Start = Töö algus
Website name =  kodulehe nimi, mis paistab välja veebilehitseja tiitliribal
Admin password = Administraatori salasõna
Go = Alusta
Files = Failid
One level up = Ülesse
Root directory = Peakaust
Choose directory: = Vali kaust:
Open = Ava
Upload: = Laadi ülesse oma failid:
Add directory name if you need to add a directory in the current one and upload files there: = Kui soovid luua kaust ja üles laadida failid, siis sisesta kausta nimi:
one more file = lisa veel üks fail
Upload = Laadi ülesse
Preferences = Põhiseaded
Website name: = Kodulehe nimi:
Admin password: = Administraatori  parool:
allow comments = luba kommenteerida
Send comment notifications to the following email: = Saada teade uue kommentaarist emailile:
Posts per page: = Postitusi leheküljel:
Design theme: = Šabloon:
Interface language: = Keel:
secret blog = muuda kodulehe teistele nähtamatuks
New post = Uus postitus
Edit post = Postituse redigeerimine
Title: = Pealkiri:
Post text: = Postitusi tekst:
Add new topic (or few comma divided): = Lisa uus teema (või mitu komaga):
or choose from saved ones: = või vali siit:
Base part of post URL address: = Põhiosa postituse URL aadressis:
Show additional options = Näita lisavõimalused
Alternate text for TITLE tag: = Alternatiivne tekst TITLE tagil:
SEO keywords: = SEO märksõnad:
SEO description: = SEO kirjeldus:
store in drafts = mustand
use as page not in the blog = kasutada leheküljena, ei pane blogi
link in the top menu = link ülemises menüüs
link in the sidebar = link kõrval menüüs
Post intro to be displayed in the blog instead of the text: = Lühiteks, mis kuvatakse blogis:
Hide additional options = Peida lisavõimalused
Done = Valmis
: reply to a comment = : Vastus kommentaarile
Reply to your comment: = Vastus teie kommentaarile:
Comment author: = Kommentaatori nimi:
E-mail of the comment author: = Kommentaatori email:
Website of the comment author: = Kommentaatori veebileht:
Comment text: = Kommentaar:
Your reply: = Teie vastus:
notify comment author about the reply = saada kommentaatorile ka teade teie vastusest
just remove the comment = kustuta see kommentaar
: new comment = : uus kommentaar
New comment at = Uus kommentaar aadressil :
: continuing discussion = : jätkub
Drafts = Mustandid
Find = Otsing


January = Jaanuar
February = Veebruar
March = Märts
April = Aprill
May = Mai
June = Juuni
July = Juuli
August = August
September = September
October = Oktoober
November = November
December = Detsember


Full text = Näita terve tekst
Edit = Redigeeri
edit = redigeeri
Your name: = Teie nimi:
Your email (for notifications): = Teie emeil (teatiste jaoks):
Your website: = Teie veebileht:
Write a comment: = Teie kommentaar:
Send = Saada
No posts here. = Siis pole postitusi.
Pages: = Lehed:
Blog = Blog
Search = Otsi
Write = Uus postitus
Exit = Logi välja
Edit the comment = Redigeeri kommentaar
Alternative main page: = Alternatiivne esileht:
Favourite = Lemmikud
in favourites = lisa lemmikutesse
Edit the sidebar = Redigeeri küljemenüü
Text before links: = Tekst enne linke:
Text after links: = Tekst pärast linke:
Page suffix (e.g. .html): = Faililaiend (näiteks, .html):
Profile photo: = Profiili pilt:
remove photo = kustuta pilt
secret post = salapostitus
Secret posts = Salapostitused
Change publication date = Muuda postituse kuupäev
hide Blog link = peida blogi link
hide Management link = peida halduse link
Powered by = Sisuhaldussüsteem on 
Edit the top menu = Redigeeri ülemine menüü
Edit the footer = Redigeeri alumine menüü
Empty this field to reset the footer: = Jäta see lahter tühjana, et taastada alumine menüü:
do not use rich text editor = mitte kasutada rikas tekstiredaktor
Place Youtube / Google Maps / audio code here: = Youtube, Google Maps, muusika jne koodid:
Read from the start = Loe algusest
Usual blog order = Tavaline blogi järjekord
premoderate comments = kommentaarid oodatakse kontrollimist administraatori poolt
Comments are premoderated. = Uued kommentaarid ennem kontrollitakse administraatori poolt.
— to moderate = — ootab kontrollimist
approve this comment = kinnita see kommentaar
use social buttons = sotsiaalsed sisselogimise nupud
template = šabloon
Edit the current template = Redigeeri see šabloon
HTML template: = HTML šabloon:
Post / page template: = Postituse / lehekülje šabloon:
raise updated posts = tõsta ülesse uuendatud postitused
Language switchers: = Keeled:
topics in sidebar = postituse teemad küljemenüüs
Posts = Blogi postitused
Pages = Blogi leheküljed
hide RSS link = peida RSS link
hide Search link = peida otsing
Copying page = Lehe kopeerimine
Copy this page = Kopeeri see leht
(edit part) = (redigeeri osa)
(edit) = (redigeeri see osa)
Editing part = Osa redigeerimine
Insert stats code = Lisa loenduri kood
stats code = statistiika kood
kB = kB
Remind password = Salasõna ununes?
Your email: = Teie e-posti aadress:
Email = e-posti aadress
Check your mailbox. = Kontrolli oma postkast.
: password reminder = : salasõna meeldetuletus
Your password: = Teie salasõna:
Send notifications to the following email: = Saada teated selle e-posti aadressile:
allow comments for this entry = luba kommenterida seda poetitust
make this entry visible for everyone = tee see kommentaar nähtav kõigile
closed website = suletud koduleht
Editing meta = Redigeeri META teegid
Alternative URL = Alternatiivne URL
Alternative heading = Alternatiivne pealkiri
Preface = Eessõna
Alternative title = Alternatiivne TITLE
Keywords = Märksõnad
Description = Kirjeldus
Deferred post = Edasilükatud post
Create new folder = Loo uus kaust
display only content in the selected language = kuva ainult sisu valitud keeles
Post language: = Postituse keeled:
post ratings = postituse hinnang
Ratings = Hinnangud
Create = Loo uus
create = loo uus
change = redigeeri
(edit menu) = (redigeeri menüü)
Editing menu = Menüü redigeerimine
log = log
Log = Log
(edit PHP code) = (redigeeri PHP-kood)
PHP code = PHP-kood
Edit the super menu = Peamenüü redigeerimine
only positive ratings = ainult positiivsed arvustused
hide Favourite link = peida lemmikute link
hide Secret posts link = peida salapostituse link
hide Drafts link = peida mustandi link
hide Files link = peida failide link
hide Comments link = peida kommentaaride link
hide Ratings link = peida loenduri link 
hide topic list = peida teemad
Create new file = Loo uus fail
MB = MB
Publish in = Postita rubriigis
main blog = põhi blog
add a blog = lisa blog
New blog title = Uue blogi nimi
blogs in sidebar = blogi nimi küljemenüüs
blogs = blogid
topics = postitusi teemad
Name = Nimetus
search in sidebar = otsing küljemenüüs
edit Meta = redigeeri META teegid
Edit Meta = Redigeeri META teegid
Motto = Deviis
Confirm, please! = Palun kinnitage!
Reset the preferences = Taasta seadet
Nickname / name: = Teie nimi:
E-mail: = Emeili aadress:
Message: = Sõnum:
Message from your website = Sõnum teie kodulehelt
Message sent. = Sõnum oli saadetud.
Cancel = Loobu
make main page = tee see leht pealeheks



Click to enlarge = Kliki suurendamiseks

Record order: = Postituste sorteerimine:
usual = tavaline
from beginning = aja algusest
random = juhuslik
alphabetical = alfabeetiline
anti-alphabetical = mitte alfabeetiline
by rating = reitingi järgi


Pagination: = Lehekülgede numeratsioon:
under the posts = postituste all
over and under the posts = postituste üleval ja all
concise = lakooniline
none = puudub
previous = eelmine
next = järgmine